name: wadirectmessage
description: "Send message to whatsapp number without save it on contact"
publish_to: 'none'
version: 1.0.4+13
environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  intl_phone_field: ^3.2.0
  dtd: ^4.0.0
  flutter_lints: ^6.0.0
  google_fonts: ^6.3.3
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  web: ^1.1.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app.png
  min_sdk_android: 21